WebCv Solution/Cv.WebUI/Areas/Admin/Controllers/ProjectsController.cs
using WebCv.Domain.Models.DataContexts;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCv.Domain.Business.ProjectsModule;
using System.Linq;
using System.Threading.Tasks;

namespace WebCv.WebUI.Areas.Admin.Controllers
{

        [Area("Admin")]
        public class ProjectsController : Controller
        {
            private readonly WebCvDbContext db;
            private readonly IMediator mediator;

            public ProjectsController(WebCvDbContext db, IMediator mediator)
            {
                this.db = db;
                this.mediator = mediator;
            }

            // GET: Admin/Projects
            public async Task<IActionResult> Index(ProjectGetAllQuery query)
            {
                var response = await mediator.Send(query);

                if (response == null)
                {
                    return NotFound();
                }


                return View(response);
            }

            // GET: Admin/Projects/Details/5
            public async Task<IActionResult> Details(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var project = await db.Projects
                    .Include(p => p.ProjectCategory)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (project == null)
                {
                    return NotFound();
                }

                return View(project);
            }

            // GET: Admin/Projects/Create
            public IActionResult Create()
            {
                ViewBag.ProjectCategoryId = new SelectList(db.ProjectCategories.Where(pc => pc.DeletedDate == null), "Id", "Name");
                return View();
            }

            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create(ProjectsCreateCommand command)
            {
                if (command.Image == null)
                {
                    ModelState.AddModelError("ImagePath", "shekil göndərilməlidir");
                }

                if (ModelState.IsValid)
                {
                    var response = await mediator.Send(command);

                    if (response.Error == false)
                    {
                        return RedirectToAction(nameof(Index));
                    }

                }

                ViewBag.ProjectCategoryId = new SelectList(db.ProjectCategories, "Id", "Name", command.ProjectCategoryId);

                return View(command);
            }

            // GET: Admin/Projects/Edit/5
            public async Task<IActionResult> Edit(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var project = await db.Projects.FindAsync(id);

                if (project == null)
                {
                    return NotFound();
                }

                ViewBag.ProjectCategoryId = new SelectList(db.ProjectCategories.Where(pc => pc.DeletedDate == null), "Id", "Name", project.ProjectCategoryId);

                var editCommand = new ProjectEditCommand();

                editCommand.Id = project.Id;
                editCommand.Name = project.Name;
                editCommand.ImagePath = project.ImagePath;
                editCommand.ProjectCategoryId = project.ProjectCategoryId;


                return View(editCommand);

            }


            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int? id, ProjectEditCommand command)
            {
                if (id != command.Id)
                {
                    return NotFound();
                }

                var response = await mediator.Send(command);

                if (response == null)
                {
                    return NotFound();
                }

                if (response.Error == false)
                {
                    return RedirectToAction(nameof(Index));
                }

                ViewBag.ProjectCategoryId = new SelectList(db.ProjectCategories.Where(pc => pc.DeletedDate == null), "Id", "Name", command.ProjectCategoryId);

                return View(command);

            }

            // GET: Admin/Projects/Delete/5
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var project = await db.Projects
                    .Include(p => p.ProjectCategory)
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (project == null)
                {
                    return NotFound();
                }

                return View(project);
            }

            // POST: Admin/Projects/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                var project = await db.Projects.FindAsync(id);
                db.Projects.Remove(project);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool ProjectExists(int id)
            {
                return db.Projects.Any(e => e.Id == id);
            }
        }
    }

WebCv Solution/Cv.WebUI/ViewComponents/About/AboutViewComponent.cs
using WebCv.Domain.Models.DataContexts;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebCv.WebUI.ViewComponents.About
{
    public class AboutViewComponent : ViewComponent
    {
        private readonly WebCvDbContext db;

        public AboutViewComponent(WebCvDbContext db)
        {
            this.db = db;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var data = await db.Abouts.ToListAsync();

            if (data == null)
            {
                return null;
            }

            return View(await Task.FromResult(data));
        }
    }
}

WebCv Solution/Cv.WebUI/ViewComponents/RecentPosts/RecentPostsViewComponent.cs
using WebCv.Domain.Business.BlogPostModule;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebCv.WebUI.AppCode.ViewComponents
{
    public class RecentPostsViewComponent : ViewComponent
    {
        private readonly IMediator mediator;

        public RecentPostsViewComponent(IMediator mediator)
        {
            this.mediator = mediator;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var query = new BlogPostRecentQuery() { Size = 3};
            var posts = await mediator.Send(query);

            return View(posts);
        }
    }
}

WebCv Solution/Cv.WebUI/Views/Shared/_Layout.cshtml
<!doctype html>
<html class="no-js" lang="en">


<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="content-type" content="text/html; charset=utf-8" />
    <meta name="author" content="M_Adnan" />
    <!-- Document Title -->
    <title>Resume / CV HTML5 Template</title>

    <!-- StyleSheets -->
    <link rel="stylesheet" href="~/assets/css/ionicons.min.css">
    <link rel="stylesheet" href="~/assets/css/bootstrap/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/css/font-awesome.min.css">
    <link rel="stylesheet" href="~/assets/css/main.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/responsive.css">

    <!-- FontsOnline -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900" rel="stylesheet">

    @RenderSection("addcss", required: false)
    <!-- JavaScripts -->
    <script src="~/assets/js/vendors/modernizr.js"></script>
    <script src="https://kit.fontawesome.com/cf7085364a.js" crossorigin="anonymous"></script>
 
</head>
<body>

    <!-- Page Wrapper -->
    <div id="wrap">

        <!-- Header -->
        <nav id="cd-lateral-nav">
            <h5 class="tittle">MotiCv</h5>
            <ul class="cd-navigation">
                <li><a asp-controller="home" asp-action="index">Index Main</a></li>
                <li><a asp-controller="home" asp-action="index">About Me</a></li>
                <li><a asp-controller="home" asp-action="resume">Resume</a></li>
                <li><a asp-controller="home" asp-action="portfolio">Portfolio</a></li>
                <li><a asp-controller="blog" asp-action="index">Blog</a></li>
                <li><a asp-controller="home" asp-action="contact">Contact Me</a></li>
                <li class="item-has-children">
                    @if (@User.Identity.IsAuthenticated)
                    {
                        <p style="padding-left:20px; margin-top: 10px;">My Account</p>
                        <a href="index.html" style="text-transform:unset;">@User.GetPrincipalName()</a>
                        <ul class="sub-menu">
                            <li><a asp-controller="account" asp-action="logout">Log out</a></li>
                        </ul>
                    }
                </li>
                @if (@User.Identity.IsAuthenticated == false)
                {
                    <li><a asp-controller="account" asp-action="signin">Sign in</a></li>
                    <li><a asp-controller="account" asp-action="register">Register</a></li>
                }
            </ul>
            @await Component.InvokeAsync("RecentPosts")
        </nav>


        <!-- End Header -->
        <!-- Content -->
        <main class="cd-main-content">
            <div id="content" class="bg">
                <div class="resume">
                    <div class="container">

                        <!-- TOP HEAD -->
                        <div style="margin-bottom:70px" class="top-head">
                            <div class="row">
                                <div class="col-sm-12"> <a id="cd-menu-trigger" href="#0"><span class="cd-menu-icon"></span></a> </div>
                            </div>
                        </div>

                        <!-- Resume -->
                        <div class="row">

                            <!-- Sidebar -->
                            <div class="col-md-4">
                                <div class="side-bar">

                                    <!-- Professional Details -->
                                    <h5 class="tittle">Professional Details</h5>
                                    <img src="~/assets/images/avatar.jpg" class="img-responsive" alt="">
                                    @await Component.InvokeAsync("About");

                                    <!-- Attachments -->
                                    <h5 class="tittle">Attachments</h5>
                                    <div class="attach bor-btm padding-25">
                                        <ul>
                                            <li>
                                                <form asp-controller="Home" asp-action="Pdf">
                                                    <p>
                                                        <img src="~/assets/images/pdf-icon.jpg" alt="" />
                                                        Curriculum-Vitae.pdf
                                                        @*<form method="post" asp-controller="Home" asp-action="Export">
                                                            <button formmethod="post" asp-controller="Home" asp-action="Export" type="submit">
                                                            <i class="fa fa-cloud-download"></i>
                                                            </button>
                                                            </form>*@
                                                        <button asp-controller="Home" asp-action="Pdf" type="submit"><i class="fa fa-eye"></i></button>


                                                    </p>
                                                </form>
                                            </li>

                                        </ul>
                                    </div>

                                    <!-- Social Profiles -->
                                    <h5 class="tittle">Social Profiles</h5>
                                    <div class="social-icon bor-btm padding-25">
                                        <ul>
                                            <li> <a href="#."> <i class="fa fa-facebook"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-google"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-twitter"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-linkedin"></i></a> </li>
                                            <li> <a href="#."> <i class="fa fa-skype"></i></a> </li>
                                        </ul>
                                    </div>


                                </div>
                            </div>

                            <!-- MAIN CONTENT -->
                            <div class="col-md-8">

                                <!-- NAV LINKS -->
                                <partial name="_Navbar" />
                                <!-- NAV LINKS END -->

                                <div class="tab-content">
                                    @RenderBody()
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
        <!-- End Content -->
        <!-- Footer -->
        <footer class="footer">
            <div class="rights">
                <p>© Copyright 2016 MotiCV. All right reserved.</p>
            </div>
        </footer>
        <!-- End Footer -->

    </div>
    <!-- End Page Wrapper -->
    <!-- JavaScripts -->
    <script src="~/assets/js/vendors/jquery/jquery.min.js"></script>
    <script src="~/assets/js/vendors/bootstrap.min.js"></script>
    <script src="~/assets/js/vendors/owl.carousel.min.js"></script>
    <script src="~/assets/js/vendors/jquery.isotope.min.js"></script>
    <script src="~/assets/js/main.js"></script>

    <!-- Begin Map Script-->
    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
    <script src="~/assets/js/vendors/map.js"></script>
    @RenderSection("addjs", required: false)
</body>

<!-- Mirrored from new.uouapps.com/remoticv/index-1.html by HTTrack Website Copier/3.x [XR&CO'2014], Sun, 19 May 2019 06:20:30 GMT -->
</html>

WebCv Solution/Cv.WebUI/Views/Shared/_Navbar.cshtml
<nav>
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#nav-tabis" aria-expanded="false"> <span class="tittle">MENU</span> <span class="fa fa-navicon icon-nav"></span> </button>
    <div class="collapse navbar-collapse" id="nav-tabis">
        <ul class="isop-filter nav nav-pills">
            <li role="presentation" >
                <a asp-controller="home" asp-action="index" class="nav-link">
                    <i class="icon-user"></i> ABOUT ME
                </a>
            </li>
            <li role="presentation">
                <a asp-controller="home" asp-action="resume" class="nav-link">
                    <i class="icon-book-open"></i>RESUME
                </a>
            </li>
            <li role="presentation">
                <a asp-controller="home" asp-action="portfolio" class="nav-link">
                    <i class="icon-rocket"></i>PORTFOLIO
                </a>
            </li>
            <li role="presentation">
                <a asp-controller="blog" asp-action="index" class="nav-link">
                    <i class="icon-note"></i>BLOG
                </a>
            </li>
            <li role="presentation">
                <a asp-controller="home" asp-action="contact" class="nav-link">
                    <i class="icon-pencil"></i>CONTACT ME
                </a>
            </li>
        </ul>
    </div>
</nav>

WebCv Solution/Cv.WebUI/Views/Shared/_Projects.cshtml
@model PortfolioViewModel

<div id="Container" class="item-space row col-3" style="height: 0px; perspective: 3000px; perspective-origin: 50% 50%; transition: height 600ms ease 0s;">

    @foreach (var item in Model.Projects)
    {
        <article class="portfolio-item mix c-@item.ProjectCategoryId" data-inter-pos-x="0" data-inter-pos-y="0" data-final-pos-x="0" data-final-pos-y="0" style="transition: all 600ms ease 0ms, opacity 600ms linear; display: inline-block; transform: translate(0px, 0px);" data-bound="true">
            <div class="portfolio-image">
                <a href="#."> <img class="img-responsive" alt="Open Imagination" src="/uploads/images/@item.ImagePath"> </a>
                <div class="portfolio-overlay style-4">
                    <div class="detail-info">
                        <div class="position-center-center">
                            <h3 class="no-margin">@item.Name</h3>
                            <span><a href="#.">@item.ProjectCategory.Name</a></span><a href="@item.Link" ." class="go"><i class="fa fa-link"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </article>
        <input hidden asp-for="@item.ProjectCategoryId" />
    }
</div>