WebCv Solution/Cv.WebUI/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebCv.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
        
    public class DashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

WebCv Solution/Cv.WebUI/Areas/Admin/Controllers/ProjectCategoriesController.cs
using WebCv.Domain.Business.ProjectCategoryModule;
using WebCv.Domain.Business.ProjectCategoryModule;
using WebCv.Domain.Models.DataContexts;
using MediatR;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Portfolio.Domain.Business.ProjectCategoryModule;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebCv.WebUI.Areas.Admin.Controllers
{

    [Area("Admin")]
   // [Authorize(Roles = "sa")]
    public class ProjectCategoriesController : Controller
    {
        private readonly WebCvDbContext db;
        private readonly IMediator mediator;

        public ProjectCategoriesController(WebCvDbContext db, IMediator mediator)
        {
            this.db = db;
            this.mediator = mediator;
        }

        // GET: Admin/ProjectCategories
        public async Task<IActionResult> Index(ProjectCategoryGetAllQuery query)
        {
            var response = await mediator.Send(query);

            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        // GET: Admin/ProjectCategories/Details/5
        public async Task<IActionResult> Details(ProjectCategoryGetSingleQuery query)
        {
            var response = await mediator.Send(query);

            if (response == null)
            {
                return NotFound();
            }

            return View(response);
        }

        // GET: Admin/ProjectCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProjectCategoryCreateCommand command)
        {
            var response = await mediator.Send(command);

            if (response == null)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/ProjectCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectCategory = await db.ProjectCategories.FindAsync(id);
            if (projectCategory == null)
            {
                return NotFound();
            }
            return View(projectCategory);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProjectCategoryEditCommand command)
        {

            var response = await mediator.Send(command);

            if (response == null)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));
        }

        // GET: Admin/ProjectCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var projectCategory = await db.ProjectCategories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (projectCategory == null)
            {
                return NotFound();
            }

            return View(projectCategory);
        }

        // POST: Admin/ProjectCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(ProjectCategoryRemoveCommand command)
        {
            var response = await mediator.Send(command);

            if (response == null)
            {
                return NotFound();
            }

            return RedirectToAction(nameof(Index));

        }

        private bool ProjectCategoryExists(int id)
        {
            return db.ProjectCategories.Any(e => e.Id == id);
        }
    }
}

WebCv Solution/Cv.WebUI/Areas/Admin/Views/ProjectCategories/Create.cshtml
@model ProjectCategory

@{
    ViewData["Title"] = "Create";
}

<!-- Page-header start -->
<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Create a project catalog</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-controller="Dashboard" asp-action="index"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-action="index">All project catalogs</a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <span>Create</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Page-header end -->
<!-- Page-body start -->
<div class="page-body">
    <div class="card">
        <div class="card-header">

            <div class="card-header-right">
                <i class="icofont icofont-spinner-alt-5"></i>
            </div>

        </div>
        <div class="card-block">
            <h4 class="sub-title">Basic Inputs</h4>

            <form method="post" autocomplete="off" enctype="multipart/form-data">
                <div class="form-group row">
                    <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-12 d-flex justify-content-end">
                        <button class="btn btn-primary mr-2">Save</button>
                        <a asp-action="index" class="btn btn-info">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WebCv Solution/Cv.WebUI/Areas/Admin/Views/ProjectCategories/Details.cshtml
@model ProjectCategory


<!-- Page-header start -->
<div class="page-header">
    <div class="row align-items-end">

        <div class="col">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-controller="Dashboard" asp-action="index"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-action="index">All project categories</a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <span>Details</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Page-header end -->
<!-- Page-body start -->
<div class="page-body">
    <div class="card">
        <div class="card-block">
            <div>
                <div class="form-group row">
                    <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <div class="form-control">
                            @Model.Name
                        </div>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-12 d-flex justify-content-end">
                        <a asp-action="index" class="btn btn-info">Cancel</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Page-body end -->

WebCv Solution/Cv.WebUI/Areas/Admin/Views/ProjectCategories/Edit.cshtml
@model ProjectCategory

@{
    ViewData["Title"] = "Edit";
}

<!-- Page-header start -->
<div class="page-header">
    <div class="row align-items-end">
       
        <div class="col">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-controller="Dashboard" asp-action="index"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-action="index">All project categories</a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <span>Edit</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Page-header end -->
<!-- Page-body start -->
<div class="page-body">
    <div class="card">
        <div class="card-block">
            <form method="post" autocomplete="off" enctype="multipart/form-data">
                <div class="form-group row">
                    <label asp-for="Name" class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                </div>

                <div class="form-group row">
                    <div class="col-12 d-flex justify-content-end">
                        <input hidden asp-for="Id" />
                        <button class="btn btn-primary mr-2">Save</button>
                        <a asp-action="index" class="btn btn-info">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

WebCv Solution/Cv.WebUI/Areas/Admin/Views/ProjectCategories/Index.cshtml
@model IEnumerable<ProjectCategory>


<div class="page-header">
    <div class="row align-items-end">
        <div class="col-lg-8">
            <div class="page-header-title">
                <div class="d-inline">
                    <h4>Project categories</h4>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="page-header-breadcrumb">
                <ul class="breadcrumb-title">
                    <li class="breadcrumb-item" style="float: left;">
                        <a asp-controller="Dashboard" asp-action="index"> <i class="feather icon-home"></i> </a>
                    </li>
                    <li class="breadcrumb-item" style="float: left;">
                        <span>Proyekt kateqoriyaları</span>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<!-- Page-body start -->
<div class="page-body">

    <!-- Horizontal-border table start -->
    <div class="card">
        <div class="card-block table-border-style">
            <div class="table-responsive">
                <table class="table table-framed table-imaged">

                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th class="operations">
                                <a asp-action="index" asp-controller="projects" class="btn btn-sm btn-success">
                                    Proyektlər
                                </a>
                                <a asp-action="Create" class="btn btn-sm btn-primary">
                                    <i class="fa fa-pen-to-square"></i>
                                </a>

                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td class="operations" style="max-width:238px;">


                                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">
                                        <i class="fa-solid fa-pen"></i>
                                    </a>

                                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-info">
                                        <i class="fa fa-eye"></i>
                                    </a>

                                    <a class="btn btn-sm btn-danger" onclick="removeEntity(@item.Id, '@item.Name')">
                                        <i class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <!-- Horizontal-border table end -->
    @Html.AntiForgeryToken()
</div>
<!-- Page-body end -->
@section addcss{
<link rel="stylesheet" href="~/libs/toastr.js/toastr.min.css" />
}

@section addjs{
<script src="~/libs/sweetalert/sweetalert.min.js"></script>
<script src="~/libs/toastr.js/toastr.min.js"></script>
<script src="~/libs/toastr.js/toastr.customize.js"></script>
<script>
    function removeEntity(id, name){
        swal(`Əminsiniz ki, '${name}' silinsin?`, {
              title: "Diqqət!",
              text: `Əminsiniz ki, '${name}' silinsin?`,
              icon: "warning",
              buttons: true,
              dangerMode: true,
              buttons: ["Xeyr", "Bəli"]
        })
        .then((value) => {

            if(value == true){

                let vToken = $("[name=__RequestVerificationToken]").val();

                let formData = new FormData();

                formData.set("__RequestVerificationToken", vToken);
                formData.set("id", id);

                $.ajax({
                    url: `@Url.Action("Delete")`,
                    type: "POST",
                    data: formData,
                    contentType: false,
                    processData: false,
                    success: function(response){
                        console.log(response);

                        if(response.error == true){
                            toastr.error(response.message, "Xeta!");
                            return;
                        }

                        location.reload();
                    },
                    error: function(errorResponse){
                        console.error(errorResponse);
                    }
                });
            }
        });
    }

    function publishDate(id, name) {
            swal(`${name} adlı məqaləni dərc etmək istəyirsiniz mi?`, {
                title: "Diqqet!",
                text: `${name} adlı məqaləni dərc etmək istəyirsiniz mi?`,
                icon: "warning",
                buttons: true,
                dangerMode: true,
                buttons: ["No", "Yes"]
            })
                .then((value) => {

                    if (value == true) {

                        let vToken = $('[name=__RequestVerificationToken]').val();

                        let formData = new FormData();
                        formData.set('__RequestVerificationToken', vToken);
                        formData.set('id', id);

                        $.ajax({
                            url: `@Url.Action("Publish")`,
                            type: 'POST',
                            data: formData,
                            contentType: false,
                            processData: false,
                            success: function (response) {
                                console.log(response)
                                if (response.error == true) {
                                    toaster.error(response.message, "Xeta");
                                    return;
                                }
                                location.reload();
                            },
                            error: function (errorResponse) {
                                console.error(errorResponse);
                            }
                        });
                    }


                });

        }
</script>
}