WebCv Solution/Cv.WebUI/Areas/Admin/Controllers/AboutsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCv.Domain.Models.DataContexts;
using WebCv.Domain.Models.Entities;
using MediatR;
using WebCv.Domain.Business.AboutModule;
using WebCv.Domain.Business.BlogPostModule;
using Microsoft.AspNetCore.Authorization;

namespace WebCv.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
   // [Authorize(Roles = "sa")]
    public class AboutsController : Controller
    {
        private readonly WebCvDbContext db;
        private readonly IMediator mediator;

        public AboutsController(WebCvDbContext db, IMediator mediator)
        {
            this.db = db;
            this.mediator = mediator;
        }

        public async Task<IActionResult> Index(AboutGetAllQuery query)
        {
            var response = await mediator.Send(query);
            return View(response);
        }

       
        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(AboutCreateCommand command)
        {
            if (ModelState.IsValid)
            {
                var response = await mediator.Send(command);

                if (response.Error == false)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(command);
        }


        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var about = await db.Abouts.FindAsync(id);
            if (about == null)
            {
                return NotFound();
            }
            return View(about);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, AboutEditCommand command)
        {
            if (id != command.Id)
            {
                return NotFound();
            }

            var response = await mediator.Send(command);

            if (response.Error == false)
            {
                return RedirectToAction(nameof(Index));
            }
            return View(command);
        }



        private bool AboutExists(int id)
        {
            return db.Abouts.Any(e => e.Id == id);
        }
    }
}

WebCv Solution/Cv.WebUI/Areas/Admin/Controllers/ContactPostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebCv.Domain.Models.DataContexts;
using WebCv.Domain.Models.Entities;
using WebCv.Domain.AppCode.Services;
using Microsoft.AspNetCore.Authorization;

namespace WebCv.WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
   // [Authorize(Roles = "sa")]
    public class ContactPostsController : Controller
    {
        private readonly WebCvDbContext db;
        private readonly EmailService emailService;

        public ContactPostsController(WebCvDbContext db,EmailService emailService)
        {
            this.db = db;
            this.emailService = emailService;
        }

        // GET: Admin/ContactPosts
        public async Task<IActionResult> Index()
        {
            return View(await db.ContactPosts.ToListAsync());
        }

        // GET: Admin/ContactPosts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactPost = await db.ContactPosts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactPost == null)
            {
                return NotFound();
            }

            return View(contactPost);
        }

  
       
        // GET: Admin/ContactPosts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var contactPost = await db.ContactPosts
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contactPost == null)
            {
                return NotFound();
            }

            return View(contactPost);
        }

        // POST: Admin/ContactPosts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var contactPost = await db.ContactPosts.FindAsync(id);
            db.ContactPosts.Remove(contactPost);
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Reply(int? id)
        {
            if (id == null)
            {
                NotFound();
            }

            var contactPost = await db.ContactPosts.FirstOrDefaultAsync(m => m.Id == id);
            if (contactPost == null)
            {
                return NotFound();
            }

            return View(contactPost);
        }

        [HttpPost]
        public async Task<IActionResult> Reply(int id, [FromForm][Bind("Name, Email, Content, Subject, Answer, EmailSubject")] ContactPost model)
        {
            var entity = db.ContactPosts.FirstOrDefault(bp => bp.Id == id && bp.AnswerDate == null);

            if (!ModelState.IsValid)
            {
                return Json(new
                {
                    error = true,
                    message = "Xeta"
                });
            }

            entity.AnswerDate = DateTime.UtcNow.AddHours(4);
            entity.Answer = model.Answer;
            entity.EmailSubject = model.EmailSubject;
            await db.SaveChangesAsync();

            await emailService.SendEmailAsync(model.Email, model.EmailSubject, model.Answer);

            return Json(new
            {
                error = false,
                message = "Your answer has been sended"
            });
        }

        private bool ContactPostExists(int id)
        {
            return db.ContactPosts.Any(e => e.Id == id);
        }
    }
}

WebCv Solution/Cv.WebUI/Areas/Admin/Views/Shared/_Sidebar.cshtml
<nav class="pcoded-navbar">
    <div class="pcoded-inner-navbar main-menu">
        <div class="pcoded-navigatio-lavel">Management</div>
        <ul class="pcoded-item pcoded-left-item">
            <li>
                <a asp-controller="dashboard" asp-action="index">
                    <span class="pcoded-micon">
                        <i class="feather icon-home"></i>
                    </span>
                    <span class="pcoded-mtext">Homepage</span>
                </a>
            </li>
            <li>
                <a asp-controller="Abouts" asp-action="index">
                    <span class="pcoded-micon">
                        <i class="fa-solid fa-address-card"></i>
                    </span>
                    <span class="pcoded-mtext">About Me</span>
                </a>
            </li>
            <li class="pcoded-hasmenu" dropdown-icon="style1" subitem-icon="style1">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="fa-solid fa-blog"></i></span>
                    <span class="pcoded-mtext">Blog Posts</span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a asp-controller="blogposts" asp-action="index">
                            <span class="pcoded-mtext">Paylaşımlar</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="blogposts" asp-action="deletedposts">
                            <span class="pcoded-mtext">Silinmiş paylaşımlar</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="brands" asp-action="index">
                            <span class="pcoded-mtext">Qadağa edilmiş sözlər</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="brands" asp-action="index">
                            <span class="pcoded-mtext">Rəy funksionallıqları</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li class="pcoded-hasmenu" dropdown-icon="style1" subitem-icon="style1">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="fa-regular fa-file"></i></span>
                    <span class="pcoded-mtext">Resume</span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a asp-controller="resumebios" asp-action="index">
                            <span class="pcoded-mtext">Bio</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="resumeskills" asp-action="index">
                            <span class="pcoded-mtext">Skills</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="resumeexperiences" asp-action="index">
                            <span class="pcoded-mtext">Experience</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="ResumeDiploms" asp-action="index">
                            <span class="pcoded-mtext">Diploma</span>
                        </a>
                    </li>
                </ul>
            </li>
            <li>
                <a asp-controller="ContactPosts" asp-action="index">
                    <span class="pcoded-micon">
                        <i class="feather icon-mail"></i>
                    </span>
                    <span class="pcoded-mtext">Messages from users</span>
                </a>
            </li>

            <li class="pcoded-hasmenu" dropdown-icon="style1" subitem-icon="style1">
                <a href="javascript:void(0)">
                    <span class="pcoded-micon"><i class="fa-solid fa-briefcase"></i></span>
                    <span class="pcoded-mtext">Portfoilo</span>
                    <span class="pcoded-mcaret"></span>
                </a>
                <ul class="pcoded-submenu">
                    <li>
                        <a asp-controller="projects" asp-action="index">
                            <span class="pcoded-mtext">Projects</span>
                        </a>
                    </li>
                    <li>
                        <a asp-controller="ProjectCategories" asp-action="index">
                            <span class="pcoded-mtext">Project Category</span>
                        </a>
                    </li>
                </ul>
            </li>

            <li>
                <a asp-controller="ContactPosts" asp-action="index">
                    <span class="pcoded-micon">
                        <i class="fa-solid fa-phone"></i>
                    </span>
                    <span class="pcoded-mtext">Contact with Admin</span>
                </a>
            </li>
        </ul>
    </div>
</nav>